### ISSUE TITLE
[feat] GATEWAY 기능 구현

### ISSUE THREAD

**Issue by sonoopy** [FIFTEEN-Logistics/fifteen-logistics#11]
## 📎 Description 
> Gateway 기능 구현

## ✅ Todo
- [x] JWT 필터 구현
- [x] API 요청 헤더에 userId, username, role 포함
- [x] 모든 인입 관리
