### ISSUE TITLE
[feat] AI 기능 구현

### ISSUE THREAD

**Issue by syhan7516** [FIFTEEN-Logistics/fifteen-logistics#16]
## 📎 Description 
> AI 연동을 위한 작업입니다.

## ✅ Todo
- [x] ai project 생성
- [x] common submodule 등록
- [x] ai api 연동
