### ISSUE TITLE
[feat] Hub 기능 구현

### ISSUE THREAD

**Issue by geon8692** [FIFTEEN-Logistics/fifteen-logistics#6]
## 📎 Description 
> Hub 도메인 개발을 위한 작업입니다.

## ✅ Todo
- [x] Entity 설정
- [x] Hub 생성 기능
- [x] Hub 조회 및 검색 기능
- [x] Hub 수정 기능
- [x] Hub 삭제 기능
